/*
 * PetSitter API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Dog struct {

	Name string `json:"name,omitempty"`

	Age int32 `json:"age,omitempty"`

	Breed string `json:"breed,omitempty"`

	Size string `json:"size,omitempty"`
}
