/*
 * PetSitter API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type JobApplication struct {

	Id int32 `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	UserId int32 `json:"user_id,omitempty"`

	JobId int32 `json:"job_id,omitempty"`
}
