openapi: 3.0.3
info:
  title: CarWash API
  version: "0.1"
tags:
  - name: Car
    description: Car related operations
paths:
  /cars:
    post:
      tags:
      - Car
      summary: Register Car
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
    get:
      tags:
      - Car    
      summary: List All Cars
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Car'  
  /cars/{id}:
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      tags:
      - Car
      summary: View Car
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
    put:
      tags:
      - Car    
      summary: Modify Car
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
    delete:
      tags:
      - Car    
      summary: Delete Car
      responses:
        '204':
          description: No Content    
components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
        make:
          type: string
        model:
          type: string
        package:
          type: string
        color:
          type: string      
        year:
          type: integer                    
        category:
          type: string      
        mileage:
          type: integer      
